mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/result', views.result, name='result'),
    path('<int:question_id>/vote', views.vote, name='vote')
]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.RESTRICT)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.db.models import F
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse

# Create your views here.
def index(request):
    questions = Question.objects.all()
    context = {'questions':questions}
    return render(request,'polls/index.html', context)
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question' : question}
    return render(request, 'polls/detail.html', context)
def result(request, question_id):
    question = get_object_or_404(Question,pk=question_id)
    context = {'question' : question}
    return render(request,'polls/result.html', context)
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        choice = Choice.objects.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {'question':question, 'error_message':'You did not select a choice.'}
        return render(request, 'polls/detail.html',context)
    else:
        choice.votes = F('votes') + 1
        choice.save()
        return HttpResponseRedirect(reverse('polls:result', args=(question_id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{question}}</h1></legend>
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id='{{choice.id}}' value="{{choice.id}}">{{choice}}<br>
            {%endfor%}
            {% if error_message%}
                <br>
                <h2 style="color: red;">{{error_message}}</h2>
            {%endif%}
            
    </fieldset> 
    <br>
    <button type="submit">Vote</button>
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<ul>
{% for question in questions %}
    <li><a href="{% url 'polls:detail' question.id%}">{{question}}</a></li>
{%endfor%}
</ul>

polls/templates/polls/result.html
<!DOCTYPE html>
<fieldset>
    <legend><h1>{{question}} Poll Result</h1></legend>
        {% for choice in question.choice_set.all %}
            <p>{{choice}} >> {{choice.votes}} vote{{choice.votes|pluralize}} </p>
        {%endfor%}
        {% if error_message%}
            <br>
            <h2 style="color: red;">{{error_message}}</h2>
        {%endif%}
        
</fieldset> 